"""Generate and install systemd user units for periodic synchronization."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import tempfile


SERVICE_NAME = "sync-box.service"
TIMER_NAME = "sync-box.timer"
GENERATED_HEADER = "# Generated by sync-box; do not edit.\n"


class SystemdUnitError(RuntimeError):
    """Raised when user-unit generation or installation cannot complete safely."""


def user_unit_directory() -> Path:
    config_home = Path(
        os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")
    ).expanduser()
    return config_home / "systemd" / "user"


def render_user_units(executable: Path) -> dict[str, str]:
    """Return installable units bound to one absolute sync-box executable."""
    resolved = executable.expanduser().resolve(strict=False)
    if not resolved.is_absolute():
        raise SystemdUnitError("The sync-box executable path must be absolute")
    if "\n" in str(resolved) or "\r" in str(resolved):
        raise SystemdUnitError("The sync-box executable path contains a newline")

    command = f"{_quote_systemd_argument(str(resolved))} run --summary-only"
    service = GENERATED_HEADER + f"""[Unit]
Description=Synchronize the configured local folder with Box
[Service]
Type=oneshot
ExecStart={command}
Restart=no
UMask=0077
StandardOutput=journal
StandardError=journal
SyslogIdentifier=sync-box
TimeoutStartSec=infinity
TimeoutStopSec=30s

"""
    timer = GENERATED_HEADER + """[Unit]
Description=Run Sync_Box approximately every 30 minutes

[Timer]
OnCalendar=*-*-* *:00,30:00
Persistent=true
RandomizedDelaySec=2m
FixedRandomDelay=true
AccuracySec=1m
Unit=sync-box.service

[Install]
WantedBy=timers.target
"""
    return {SERVICE_NAME: service, TIMER_NAME: timer}


def install_user_units(executable: Path, directory: Path | None = None) -> Path:
    """Atomically install units and reload the user manager without enabling them."""
    destination = directory or user_unit_directory()
    destination.mkdir(mode=0o700, parents=True, exist_ok=True)
    units = render_user_units(executable)
    _ensure_managed(destination, units)
    for name, contents in units.items():
        target = destination / name
        _atomic_write(target, contents)
    _daemon_reload()
    return destination


def uninstall_user_units(directory: Path | None = None) -> Path:
    """Remove generated units and reload; never stop or disable a unit."""
    destination = directory or user_unit_directory()
    _ensure_managed(destination, {SERVICE_NAME: "", TIMER_NAME: ""})
    for name in (SERVICE_NAME, TIMER_NAME):
        target = destination / name
        if not target.exists():
            continue
        target.unlink()
    _daemon_reload()
    return destination


def find_invoked_executable(argv_zero: str) -> Path:
    """Resolve the console script that invoked the systemd setup command."""
    if os.sep in argv_zero:
        candidate = Path(argv_zero)
    else:
        found = shutil.which(argv_zero)
        if found is None:
            raise SystemdUnitError(f"Cannot resolve executable: {argv_zero}")
        candidate = Path(found)
    resolved = candidate.expanduser().resolve(strict=False)
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        raise SystemdUnitError(f"Executable is unavailable: {resolved}")
    return resolved


def _quote_systemd_argument(value: str) -> str:
    # Percent is a systemd specifier prefix even inside quotes.
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    return f'"{escaped}"'


def _ensure_managed(directory: Path, units: dict[str, str]) -> None:
    for name in units:
        target = directory / name
        if target.exists() and not target.read_text(encoding="utf-8").startswith(
            GENERATED_HEADER
        ):
            raise SystemdUnitError(f"Refusing to modify unmanaged unit: {target}")


def _atomic_write(path: Path, contents: str) -> None:
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(contents)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.replace(path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _daemon_reload() -> None:
    try:
        result = subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError as exc:
        raise SystemdUnitError("Could not run systemctl --user daemon-reload") from exc
    if result.returncode != 0:
        detail = " ".join(result.stderr.split())
        raise SystemdUnitError(
            "systemctl --user daemon-reload failed" + (f": {detail}" if detail else "")
        )
